#! /bin/sh
pgrep -x sxhkd >/dev/null || sxhkd &
~/.config/dunst/load.sh &
~/.config/polybar/launch.sh float &
picom --experimental-backends &
dunst &
nitrogen --restore &
mpd &


#bspc monitor -d  爵    ﴬ   漣
#bspc monitor -d         
#bspc monitor -d 一 二 三 四 五 六 七 八 九 十
bspc monitor -d 1 2 3 4 5 6 7 8 9
# bspc config automatic_scheme spiral
#bspc config initial_polarity first_child
#bspc config border_width 5
bspc config window_gap 10
bspc config border_radius 13

bspc config focused_border_color "#5e81ac"
bspc config presel_feedback_color "2e3340"
bspc config normal_border_color "#2e3440"

bspc config focus_follows_pointer true
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle false

bspc config top_padding 5
bspc config left_padding 15
bspc config right_padding 15
bspc config bottom_padding 15

# Specific settings per app
bspc rule -a Zathura state=tiled follow=on
bspc rule -a Nitrogen state=floating follow=on center=true rectangle=600x400+0+0

bspc rule -a notion-app-enhanced desktop='^6' follow=off
bspc rule -a discord desktop='^8' follow=on
bspc rule -a TelegramDesktop desktop='^8' follow=on
bspc rule -a Caprine desktop='^8' follow=on
bspc rule -a pomotroid state=floating rectangle=600+503+145

bspc rule -a Spotify desktop='^7' follow=on
bspc rule -a qBittorrent desktop='^9' follow=on

bspc rule -a Font-manager state=floating follow=on center=true
bspc rule -a Gnome-calculator state=floating follow=on center=true rectangle=400x400+0+0
